const expectedMinutes=require('./participation-test-helper.cjs');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const F=require('./dist/engine.js'),E=require('./dist/economy.js'),S=require('./dist/season.js'),P=require('./dist/cup.js'),O=require('./dist/opposition.js');
function canonicalNames(value){const out=JSON.parse(JSON.stringify(value));const visit=o=>{if(!o||typeof o!=='object')return;if(typeof o.name==='string'){const p=F.identityProfile(o.identity||o.id);if(p)o.name=p.name;}for(const v of Object.values(o))visit(v);};visit(out);return out;}
let checks=0;
const test=(name,fn)=>{fn();checks++;console.log('PASS '+name);};
const clone=x=>JSON.parse(JSON.stringify(x));
function play(s){const m=s.match;while(m.phase!=='full'){if(!F.running(m))F.begin(m);F.finishSegment(m);}return s;}
function complete(s,train=true){while(s.match){if(train&&s.competition!=='cup'&&!s.trained)S.train(s,['technique','pace','fitness','recovery'][s.round%4]);play(s);s=S.settle(s);}return s;}
function finishCups(s){while(s.competition==='cup'){play(s);s=S.settle(s);}return s;}
test('legacy divisions keep their 14-round schedules while the expanded world has 116 clubs',()=>{for(const division of [1,2]){const state={league:{division}},fixtures=S.fixturesFor(state);assert.equal(fixtures.length,14);const pairs=new Set();for(const round of fixtures){assert.equal(round.length,4);assert.equal(new Set(round.flatMap(f=>[f.home,f.away])).size,8);for(const f of round){assert.notEqual(f.home,f.away);const key=f.home+'/'+f.away;assert.ok(!pairs.has(key));pairs.add(key);}}assert.equal(pairs.size,56);for(const club of S.leagueClubs(state)){assert.equal(fixtures.flat().filter(f=>f.home===club.id).length,7);assert.equal(fixtures.flat().filter(f=>f.away===club.id).length,7);}}assert.equal(S.clubs.length,116);assert.deepEqual(S.fixtures,S.fixturesFor({league:{division:2}}));});
test('2026/27 five-tier schedules give every club a full home-and-away season',()=>{for(const division of [1,2,3,4,5]){const fullIds=S.fiveTierPools[division].map(c=>c.id),coreIds=fullIds.slice(0,8),rounds=S.fixturesFor({league:{division,rules:'five-tier',clubIds:fullIds}}),legacy=S.fixturesFor({league:{division,rules:'five-tier',clubIds:coreIds}}),teams=fullIds.length;assert.equal(teams,division===1?20:24);assert.equal(rounds.length,teams*2-2);assert.equal(rounds[0].length,teams/2);for(let r=0;r<14;r++)assert.deepEqual(rounds[r].slice(0,4),legacy[r]);const pairs=new Set();for(const row of rounds){assert.equal(row.length,teams/2);assert.equal(new Set(row.flatMap(f=>[f.home,f.away])).size,teams);for(const f of row){const key=f.home+'/'+f.away;assert.ok(!pairs.has(key));pairs.add(key);}}assert.equal(pairs.size,teams*(teams-1));for(const id of fullIds){assert.equal(rounds.flat().filter(f=>f.home===id).length,teams-1);assert.equal(rounds.flat().filter(f=>f.away===id).length,teams-1);}}const fresh=S.create(1002,{startingClub:true});assert.equal(S.roundCount(fresh),46);assert.equal(S.fixturesFor(fresh).length,46);});
test('training applies once, changes the active squad, and rejects mid-match mutation',()=>{const s=S.create(),before=clone(s);S.train(s,'pace');for(const p of Object.values(s.squad)){assert.equal(p.speed,Math.min(99,before.squad[p.id].speed+1));assert.equal(s.match.players[p.id].speed,p.speed);assert.equal(s.match.players[p.id].initialEnergy,p.energy);}let unchanged=JSON.stringify(s);assert.throws(()=>S.train(s,'recovery'));assert.equal(JSON.stringify(s),unchanged);const t=S.create();F.begin(t.match);unchanged=JSON.stringify(t);assert.throws(()=>S.train(t,'technique'));assert.equal(JSON.stringify(t),unchanged);});
test('a round settles 4 games once and maps away scores correctly',()=>{let s=S.create();assert.throws(()=>S.settle(s));play(s);const score=[...s.match.score],before=JSON.stringify(s);s=S.settle(s);assert.equal(s.round,1);assert.equal(s.results.length,4);assert.deepEqual(s.results.find(r=>r.home===S.own).goals,score);assert.equal(s.match.isHome,false);assert.throws(()=>S.settle(s));assert.equal(s.results.length,4);play(s);const awayScore=[...s.match.score];s=S.settle(s);assert.deepEqual(s.results.find(r=>r.round===1&&r.away===S.own).goals,[awayScore[1],awayScore[0]]);assert.equal(S.restore(JSON.parse(before)).round,0);});
test('full seasons have coherent standings and conserved goals',()=>{for(let seed=1;seed<=24;seed++){const s=complete(S.create(seed)),table=S.standings(s);assert.equal(s.results.length,56);assert.equal(s.match,null);assert.equal(table.reduce((n,c)=>n+c.played,0),112);assert.equal(table.reduce((n,c)=>n+c.gd,0),0);assert.equal(table.reduce((n,c)=>n+c.gf,0),table.reduce((n,c)=>n+c.ga,0));for(const c of table){assert.equal(c.played,14);assert.equal(c.won+c.drawn+c.lost,14);assert.equal(c.points,c.won*3+c.drawn);}}});
test('restoring a finished campaign keeps its season until the player explicitly starts the next one',()=>{const finished=complete(S.create(20261006)),restored=S.restore(clone(finished));assert.equal(S.ready(finished),true);assert.equal(S.ready(restored),true);assert.equal(restored.year,finished.year);assert.equal(restored.round,finished.round);assert.deepEqual(restored.results,finished.results);assert.deepEqual(restored.history,finished.history);assert.deepEqual(restored.match,finished.match);const next=S.nextSeason(restored);assert.equal(next.year,finished.year+1);assert.equal(next.round,0);assert.equal(next.history.length,finished.history.length+1);});
test('experience, development and recovery apply to actual participation',()=>{let s=S.create();for(let round=0;round<3;round++){const m=s.match;if(m.lineup.includes('f3'))F.swap(m,'f3','f1');F.begin(m);F.finishSegment(m);F.swap(m,'f1','f3');play(s);const energies=Object.fromEntries(Object.entries(m.players).map(([id,p])=>[id,p.energy]));s=S.settle(s);for(const p of Object.values(s.squad))assert.equal(p.energy,Math.min(100,energies[p.id]+32));}assert.equal(s.squad.g1.xp,270);assert.equal(s.squad.g2.xp,0);assert.equal(s.squad.g1.keeping,F.roster.find(p=>p.id==='g1').keeping+1);assert.equal(s.squad.g2.keeping,F.roster.find(p=>p.id==='g2').keeping);assert.equal(Object.values(s.squad).reduce((n,p)=>n+p.xp,0),expectedMinutes(s.statistics.records));});
test('restore preserves trained skills and deterministic play at 0/17/45/65/90',()=>{for(const stop of [0,17,45,65,90]){let a=S.create(842);S.train(a,'technique');while(a.match.minute<stop){if(!F.running(a.match))F.begin(a.match);F.tick(a.match);}let b=S.restore(clone(a));assert.equal(b.squad.m2.passing,a.squad.m2.passing);assert.equal(b.match.players.m2.passing,a.match.players.m2.passing);assert.equal(b.match.players.f1.initialEnergy,a.match.players.f1.initialEnergy);b.match.paused=false;play(a);play(b);assert.deepEqual(a.match.score,b.match.score);assert.deepEqual(a.match.logs,b.match.logs);a=S.settle(a);b=S.settle(b);assert.deepEqual(a,b);assert.deepEqual(S.restore(clone(a)),a);}});
test('growth and history carry across seasons, while match counters reset',()=>{const first=complete(S.create()),second=S.nextSeason(first);assert.equal(second.year,2);assert.equal(second.round,0);assert.equal(second.history.length,1);assert.equal(second.results.length,0);assert.equal(second.match.minute,0);assert.equal(second.match.subs,0);assert.equal(second.match.logs.length,0);for(const p of Object.values(second.squad)){assert.equal(p.energy,100);assert.equal(p.xp,first.squad[p.id].xp);assert.equal(p[S.primaryKey(p)],first.squad[p.id][S.primaryKey(p)]);}assert.deepEqual(S.restore(clone(first)),first);assert.deepEqual(S.restore(clone(second)),second);let s=second;for(let i=0;i<3;i++){s=complete(s);s=S.nextSeason(s);}assert.equal(s.history.length,4);for(const p of Object.values(s.squad))for(const key of ['attack','defense','passing','keeping','speed','endurance'])assert.ok(p[key]>=0&&p[key]<=99);});
test('broken round, result references, skills, match seed and duplicate scores are rejected',()=>{let s=S.settle(play(S.create()));for(const mutate of [x=>x.round=2,x=>x.results.push(x.results[0]),x=>x.results[0].home='unknown',x=>x.results[0].goals=[-1,0],x=>x.match.seed++,x=>x.squad.f1.attack=100,x=>x.match.players.f1.attack++,x=>x.match.players.f1.initialEnergy=999,x=>x.history.push({})]){const bad=clone(s);mutate(bad);assert.throws(()=>S.restore(bad));}const good=clone(s);good.standings=[{points:999}];assert.deepEqual(S.standings(S.restore(good)),S.standings(s));});
test('damaged full-time substitutions and ratings cannot break result rendering',()=>{const s=S.create();F.begin(s.match);F.finishSegment(s.match);F.swap(s.match,'f1','f3');F.setTactic(s.match,'counter');play(s);for(const mutate of [x=>x.match.decisions[0].in='missing',x=>x.match.segments[1].rating={paceBonus:0},x=>x.plan.lineup=['g1','g2','d1','d2','d3','d4','d5','d6','m1','m2','m3']]){const bad=clone(s);mutate(bad);assert.throws(()=>S.restore(bad));}});
test('every opponent and venue reaches the match engine with deterministically accumulated league cards',()=>{let s=S.create();for(let r=0;r<14;r++){const shown=S.opponentFor(s),opp=S.rawClub(shown.id),base=O.profile(opp);assert.deepEqual(s.match.opponent,O.rivalEffect(s,opp,base).profile);assert.equal(s.match.opponentName,opp.name);assert.equal(s.match.isHome,S.fixtureFor(s).home===S.own);s=finishCups(S.settle(play(s)));}});
test('v6 saves preserve past lower-league titles and the current match through every decision phase',()=>{
 const context=vm.createContext({}),base=path.join(__dirname,'legacy-v6');for(const file of ['engine.js','economy.js','career.js','cup.js','health.js','season.js'])vm.runInContext(fs.readFileSync(path.join(base,file),'utf8'),context,{filename:'legacy-v6-'+file});const old=context.Season,engine=context.Football;
 let original=old.create(121);for(const p of Object.values(original.squad)){for(const key of ['attack','defense','passing','speed','endurance','keeping']){p[key]=99;original.match.players[p.id][key]=99;}p.potential=99;p.energy=100;original.career.baselines[p.identity]=99;Object.assign(original.match.players[p.id],{potential:99,energy:100,initialEnergy:100});}
 while(original.match){while(original.match.phase!=='full'){if(!engine.running(original.match))engine.begin(original.match);engine.finishSegment(original.match);}original=old.settle(original);}assert.equal(old.standings(original).find(c=>c.id===S.own).rank,1);original=old.nextSeason(original);original=old.scout(original,'GK');original=old.recruit(original,'t_d2','d6');
 for(const stop of [0,17,45,65,90]){const raw=clone(original);while(raw.match.minute<stop){if(!engine.running(raw.match))engine.begin(raw.match);engine.tick(raw.match);}const migrated=S.restore(clone(raw));assert.equal(migrated.version,10);assert.deepEqual(migrated.league,{version:1,division:2,rules:'legacy'});assert.equal(migrated.history[0].rank,1);assert.deepEqual(S.leagueForYear(migrated,1),{division:2,rules:'legacy'});assert.equal(migrated.history[0].nextDivision,2);assert.deepEqual(migrated.match,canonicalNames({...raw.match,version:5,statisticsOriginMinute:raw.match.minute,paused:engine.running(raw.match)}));assert.deepEqual(migrated.finance,raw.finance);assert.deepEqual(migrated.squad,canonicalNames(raw.squad));assert.deepEqual(migrated.career,raw.career);assert.deepEqual(migrated.health,canonicalNames(raw.health));assert.deepEqual(migrated.cup,raw.cup);assert.deepEqual(S.restore(clone(migrated)),migrated);}
 const migrated=S.restore(clone(original)),finished=complete(migrated,false),next=S.nextSeason(finished),move=S.movement(finished);assert.equal(next.league.rules,'pyramid');assert.equal(next.league.division,move.to);assert.equal(next.history.at(-1).nextDivision,move.to);assert.equal(next.history[0].nextDivision,2);assert.deepEqual(S.restore(clone(next)),next);
});
test('division metadata rejects incompatible fixtures, jumps and changed historical membership',()=>{
 const fresh=S.create();for(const mutate of [x=>x.league.division=1,x=>x.league.division=3,x=>x.league.version=2,x=>x.league.rules='other',x=>delete x.league]){const bad=clone(fresh);mutate(bad);assert.throws(()=>S.restore(bad));}
 const finished=complete(S.create(17)),next=S.nextSeason(finished);for(const mutate of [x=>x.history[0].division=1,x=>x.history[0].nextDivision=x.history[0].nextDivision===1?2:1,x=>x.history[0].champion='calderwick',x=>x.league.division=x.league.division===1?2:1,x=>x.league.rules='legacy']){const bad=clone(next);mutate(bad);assert.throws(()=>S.restore(bad));}
});
test('midseason restore keeps played rounds, receipts and the exact in-progress match',()=>{let saved=S.create(20261006);while(saved.round<5){if(saved.competition==='cup'){saved=finishCups(saved);continue;}saved=S.settle(play(saved));}assert.equal(saved.year,1);assert.equal(saved.round,5);while(saved.match.minute<37){if(!F.running(saved.match))F.begin(saved.match);F.tick(saved.match);}const restored=S.restore(clone(saved));assert.equal(restored.year,saved.year);assert.equal(restored.round,saved.round);assert.deepEqual(restored.results,saved.results);assert.deepEqual(restored.finance,saved.finance);const expectedMatch=clone(saved.match);expectedMatch.paused=true;assert.deepEqual(restored.match,expectedMatch);saved.match.paused=false;restored.match.paused=false;play(saved);play(restored);assert.deepEqual(S.settle(saved),S.settle(restored));});
test('compact eight-club prototype saves expand in place and preserve results, finances, cup gates and the live match',()=>{let saved=S.create(20261007,{startingClub:true});delete saved.cup.calendarRounds;while(saved.round<3)saved=S.settle(play(saved));while(saved.match.minute<37){if(!F.running(saved.match))F.begin(saved.match);F.tick(saved.match);}const compact=clone(saved),perRound=saved.league.clubIds.length/2;compact.version=10;compact.league.clubIds=compact.league.clubIds.slice(0,8);compact.results=Array.from({length:compact.round},(_,round)=>saved.results.slice(round*perRound,round*perRound+4)).flat();const restored=S.restore(compact);assert.equal(restored.year,saved.year);assert.equal(restored.round,saved.round);assert.equal(restored.league.clubIds.length,24);assert.equal(S.roundCount(restored),46);assert.deepEqual([0,1,2].map(stage=>P.gateFor(restored,stage)),[4,8,12]);assert.deepEqual(restored.results,saved.results);assert.deepEqual(restored.finance,saved.finance);const expected=clone(saved.match);expected.paused=true;assert.deepEqual(restored.match,expected);assert.deepEqual(S.restore(clone(restored)),restored);saved.match.paused=false;restored.match.paused=false;play(saved);play(restored);assert.deepEqual(S.settle(saved),S.settle(restored));});
test('a completed 14-round prototype keeps its season and earned goal payment while continuing at round 15',()=>{let expanded=S.create(20261008,{startingClub:true});delete expanded.cup.calendarRounds;while(expanded.round<14||expanded.competition==='cup')expanded=S.settle(play(expanded));const compact=clone(expanded),gamesPerRound=expanded.league.clubIds.length/2;compact.league.clubIds=compact.league.clubIds.slice(0,8);compact.results=Array.from({length:14},(_,round)=>expanded.results.slice(round*gamesPerRound,round*gamesPerRound+4)).flat();compact.match=null;compact.competition='league';const outcome=E.goal(compact,S.standings(compact));compact.finance.outcome=outcome;compact.finance.balance+=outcome.bonus;compact.finance.ledger.push({id:'goal-'+compact.year,type:'goal',year:compact.year,round:14,amount:outcome.bonus,...outcome});const restored=S.restore(compact);assert.equal(restored.year,compact.year);assert.equal(restored.round,14);assert.equal(restored.match.phase,'prep');assert.equal(S.roundCount(restored),46);assert.deepEqual([0,1,2].map(stage=>P.gateFor(restored,stage)),[4,8,12]);for(let round=0;round<14;round++)assert.deepEqual(restored.results.filter(r=>r.round===round).filter(r=>compact.league.clubIds.includes(r.home)&&compact.league.clubIds.includes(r.away)),compact.results.filter(r=>r.round===round));assert.equal(restored.finance.balance,compact.finance.balance);assert.equal(restored.finance.ledger.at(-1).type,'goal-migration');assert.equal(restored.finance.ledger.at(-1).amount,outcome.bonus);assert.equal(restored.finance.outcome,null);assert.equal(restored.match.opponentName,S.opponentFor(restored).name);assert.deepEqual(S.restore(clone(restored)),restored);});
console.log('Validated '+checks+' season groups, including 24 full seasons plus persistence and progression checks.');
