'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const F=require('./dist/engine.js'),E=require('./dist/economy.js'),S=require('./dist/season.js');
const Cup=globalThis.Cup||require('./dist/cup.js'),C=globalThis.Career;
const copy=x=>JSON.parse(JSON.stringify(x));let checks=0;
function canonicalNames(value){const out=JSON.parse(JSON.stringify(value));const visit=o=>{if(!o||typeof o!=='object')return;if(typeof o.name==='string'){const p=F.identityProfile(o.identity||o.id);if(p)o.name=p.name;}for(const v of Object.values(o))visit(v);};visit(out);return out;}
function displayLogs(logs,players){return JSON.parse(JSON.stringify(logs)).map(e=>({...e,text:F.displayText(e.text,players)}));}
function legacySquad(squad){return Object.fromEntries(Object.entries(canonicalNames(squad)).map(([id,p])=>[id,{...p,injury:null}]));}
function test(name,fn){fn();checks++;console.log('PASS '+name);}
function finish(m,engine=F){while(m.phase!=='full'){if(!engine.running(m))engine.begin(m);engine.finishSegment(m);}return m;}
function settleMatch(s){finish(s.match);return S.settle(s);}
function finishCups(s){while(s.competition==='cup')s=settleMatch(s);return s;}
function leagueRound(s){s=finishCups(s);return finishCups(settleMatch(s));}
function complete(s){while(s.match)s=settleMatch(s);return s;}
function firstCup(seed=20260930){let s=S.create(seed);while(s.competition!=='cup'&&s.match)s=settleMatch(s);assert.equal(s.competition,'cup');assert.equal(s.round,4);return s;}
function rejectAtomic(s,fn){const before=JSON.stringify(s);assert.throws(()=>fn(s));assert.equal(JSON.stringify(s),before);}
function legacy(){const ctx=vm.createContext({}),base=path.join(__dirname,'legacy-v4');for(const file of ['engine.js','economy.js','career.js','season.js'])vm.runInContext(fs.readFileSync(path.join(base,file),'utf8'),ctx,{filename:'v4-'+file});return {F:ctx.Football,E:ctx.Economy,C:ctx.Career,S:ctx.Season};}
function ownResults(s){return s.cup.results.filter(r=>r.home===S.own||r.away===S.own);}
function boosted(seed){const s=S.create(seed);for(const p of Object.values(s.squad)){for(const key of ['attack','defense','passing','speed','endurance','keeping']){p[key]=99;s.match.players[p.id][key]=99;}p.potential=99;p.energy=100;s.career.baselines[p.identity]=99;s.match.players[p.id].potential=99;s.match.players[p.id].energy=100;s.match.players[p.id].initialEnergy=100;}return s;}
function assertMatchPreserved(a,b){for(const k of ['seed','rng','phase','minute','formation','tactic','isHome','score','shots','chances','xg','logs','segments','lineup','out','subs','decisions'])assert.deepEqual(a[k],copy(b[k]),k);const players=canonicalNames(b.players);for(const p of Object.values(players))p.injuryRemaining??=0;assert.deepEqual(a.players,players);}

test('each season has one deterministic eight-club knockout bracket and three league gates',()=>{
 const s=S.create(543),again=S.create(543);assert.equal(s.version,8);assert.equal(s.competition,'league');assert.equal(s.cup.version,1);assert.equal(s.cup.originRound,0);assert.equal(s.cup.enabled,true);assert.equal(s.cup.stage,0);assert.equal(s.cup.champion,null);assert.deepEqual(s.cup.results,[]);assert.deepEqual(Cup.gates,[4,8,12]);assert.deepEqual(s.cup.bracket,again.cup.bracket);assert.equal(new Set(s.cup.bracket).size,8);assert.deepEqual([...s.cup.bracket].sort(),S.leagueClubs(s).map(c=>c.id).sort());assert.equal(Cup.due(s),false);assert.deepEqual(S.restore(copy(s)),s);
 const fixtures=Cup.fixturesFor(s,0);assert.equal(fixtures.length,4);assert.equal(new Set(fixtures.flatMap(f=>[f.home,f.away])).size,8);assert.ok(fixtures.every(f=>f.home!==f.away));
});

test('cups insert after rounds 4, 8 and 12 and AI finishes the bracket after elimination',()=>{
 let s=S.create(544);while(s.match){const beforeRound=s.round,wasCup=s.competition==='cup';if(wasCup){assert.ok([4,8,12].includes(s.round));assert.equal(s.results.length,s.round*4);}s=settleMatch(s);if(wasCup)assert.equal(s.round,beforeRound);else assert.equal(s.round,beforeRound+1);}
 assert.equal(s.round,14);assert.equal(s.results.length,56);assert.equal(s.cup.stage,3);assert.equal(s.cup.results.length,7);assert.ok(S.club(s.cup.champion));for(const [stage,count] of [[0,4],[1,2],[2,1]]){const r=s.cup.results.filter(x=>x.stage===stage);assert.equal(r.length,count);assert.ok(r.every(x=>x.week===Cup.gates[stage]));assert.equal(new Set(r.flatMap(x=>[x.home,x.away])).size,count*2);if(stage)assert.deepEqual(r.flatMap(x=>[x.home,x.away]).sort(),s.cup.results.filter(x=>x.stage===stage-1).map(x=>x.winner).sort());}assert.doesNotThrow(()=>S.restore(copy(s)));
});

test('cup lineups support every formation, stop at 90 minutes and preserve bench and substitution minutes',()=>{
 for(const formation of ['442','433','352']){let s=firstCup(545);F.setFormation(s.match,formation);F.begin(s.match);F.finishSegment(s.match);const outgoing=s.match.lineup.find(id=>s.match.players[id].pos==='FW'),incoming=Object.keys(s.match.players).find(id=>s.match.players[id].pos==='FW'&&!s.match.lineup.includes(id));F.swap(s.match,outgoing,incoming);finish(s.match);assert.equal(s.match.minute,90);assert.equal(s.match.players[outgoing].minutes,45);assert.equal(s.match.players[incoming].minutes,45);assert.equal(s.match.players.g2.minutes,0);assert.equal(Object.values(s.match.players).reduce((n,p)=>n+p.minutes,0),990);const n=S.settle(s);assert.equal(n.round,4);assert.equal(n.plan.formation,formation);assert.doesNotThrow(()=>S.restore(copy(n)));}
});

test('cup results and recovery add experience without changing league results, points or win objectives',()=>{
 let s=firstCup(546);const before=copy(s),table=S.standings(s),progress=C.progress(s);finish(s.match);const played=copy(s.match.players),score=copy(s.match.score),preview=Cup.preview(s,s.match);s=S.settle(s);assert.equal(s.round,before.round);assert.deepEqual(s.results,before.results);assert.deepEqual(S.standings(s),table);assert.equal(C.progress(s).wins,progress.wins);assert.deepEqual(ownResults(s).at(-1).goals,before.match.isHome?score:[score[1],score[0]]);assert.deepEqual(ownResults(s).at(-1),preview);
 for(const p of Object.values(s.squad)){assert.equal(p.energy,Math.min(100,played[p.id].energy+20));assert.equal(p.xp,before.squad[p.id].xp+played[p.id].minutes);assert.equal(s.career.minutes[p.identity],before.career.minutes[p.identity]+played[p.id].minutes);assert.ok(p[F.roleKey(p)]<=p.potential);}assert.equal(Object.values(s.career.minutes).reduce((n,x)=>n+x,0),990*5);assert.equal(s.trained,before.trained);assert.equal(s.finance.transferWeek,before.finance.transferWeek);assert.doesNotThrow(()=>S.restore(copy(s)));
});

test('cup income uses its own gate and advance bonus, charges no additional wages and pays only once',()=>{
 const venues=[];for(const seed of [547,77]){let s=firstCup(seed);finish(s.match);const before=copy(s),preview=Cup.preview(s,s.match),won=preview.winner===S.own;venues.push(before.match.isHome);s=S.settle(s);const e=s.finance.ledger.find(x=>x.type==='cup');assert.ok(e);assert.equal(e.round,4);assert.equal(e.stage,0);assert.equal(e.gate,before.match.isHome?18000:8000);assert.equal(e.advanceBonus,won?12000:0);assert.equal(e.income,e.gate+e.advanceBonus);assert.equal(e.amount,e.income);assert.ok(!Object.hasOwn(e,'payroll'));assert.equal(s.finance.balance,before.finance.balance+e.amount);assert.equal(s.finance.ledger.filter(x=>x.type==='match').length,4);assert.equal(s.finance.ledger.filter(x=>x.type==='cup').length,1);rejectAtomic(s,x=>E.applyCup(x,ownResults(x).at(-1)));assert.doesNotThrow(()=>S.restore(copy(s)));}assert.deepEqual(venues,[true,false]);
});

test('cup preparation forbids league-week training, recruitment and scouting without partial mutation',()=>{
 const s=firstCup(548);assert.equal(s.match.phase,'prep');const before=JSON.stringify(s);assert.doesNotThrow(()=>E.quote(s,'t_f2','f1'));assert.equal(JSON.stringify(s),before);rejectAtomic(s,x=>S.train(x,'technique'));rejectAtomic(s,x=>S.train(x,'recovery'));rejectAtomic(s,x=>S.recruit(x,'t_f2','f1'));rejectAtomic(s,x=>E.recruit(x,'t_g2','g2'));rejectAtomic(s,x=>S.scout(x,'FW'));rejectAtomic(s,x=>E.payScout(x,'FW',1));const n=settleMatch(s);assert.equal(n.competition,'league');assert.equal(n.round,4);assert.doesNotThrow(()=>S.train(n,'recovery'));assert.doesNotThrow(()=>S.recruit(n,'t_g2','g2'));
});

test('tied cup matches have deterministic decisive shootouts across save and resume',()=>{
 let s=firstCup(549);finish(s.match);assert.deepEqual(s.match.score,[1,1],'fixture must produce a real regulation draw');const before=JSON.stringify(s),a=Cup.preview(s,s.match),b=Cup.preview(S.restore(copy(s)),copy(s.match));assert.equal(JSON.stringify(s),before);assert.deepEqual(a,b);assert.ok(Array.isArray(a.penalties));assert.notEqual(a.penalties[0],a.penalties[1]);assert.equal(a.winner,a.penalties[0]>a.penalties[1]?a.home:a.away);assert.equal(a.kicks.length,2);assert.ok(a.kicks.every(team=>team.every(k=>typeof k==='boolean')));for(let i=0;i<2;i++)assert.equal(a.kicks[i].filter(Boolean).length,a.penalties[i]);
 for(const stop of [0,45,65,90]){let original=firstCup(549);while(original.match.minute<stop){if(!F.running(original.match))F.begin(original.match);F.finishSegment(original.match);}const restored=S.restore(copy(original));assertMatchPreserved(restored.match,original.match);finish(original.match);finish(restored.match);const r1=S.settle(original),r2=S.settle(restored);assert.deepEqual(r1,r2);assert.doesNotThrow(()=>S.restore(copy(r1)));}
});

test('cup participation helps a youth objective and does not transfer minutes to a replacement',()=>{
 let s=S.create(550);for(let r=0;r<3;r++)s=leagueRound(s);s=S.scout(s,'FW');const id=s.career.reports[0].candidates[0];s=S.recruit(s,id,'f1');s=settleMatch(s);assert.equal(s.competition,'cup');assert.equal(s.career.minutes[id],90);s=settleMatch(s);assert.equal(s.career.minutes[id],180);assert.equal(s.career.missions.youth,null);s=leagueRound(s);assert.equal(s.career.minutes[id],270);assert.equal(s.career.missions.youth,5);assert.equal(s.finance.ledger.filter(e=>e.type==='board'&&e.task==='youth').length,1);s=S.recruit(s,'t_f2','f1');assert.equal(s.squad.f1.xp,0);assert.equal(s.career.minutes.t_f2,0);assert.equal(s.career.minutes[id],270);assert.equal(C.progress(s).youth,270);assert.doesNotThrow(()=>S.restore(copy(s)));
});

test('corrupt cup brackets, stages, winners, shootouts and cash rows are rejected',()=>{
 let s=settleMatch(firstCup(549));const corrupt=fn=>{const x=copy(s);fn(x);assert.throws(()=>S.restore(x));};corrupt(x=>x.cup.bracket[1]=x.cup.bracket[0]);corrupt(x=>x.cup.bracket[0]='unknown');corrupt(x=>x.cup.stage=-1);corrupt(x=>x.cup.stage=4);corrupt(x=>x.cup.results.push(copy(x.cup.results[0])));corrupt(x=>x.cup.results[0].winner='unknown');corrupt(x=>x.cup.results[0].week=1);corrupt(x=>x.cup.results[0].index=99);corrupt(x=>x.cup.champion=S.own);corrupt(x=>{const e=x.finance.ledger.find(r=>r.type==='cup');e.amount++;e.income++;x.finance.balance++;});corrupt(x=>{const i=x.finance.ledger.findIndex(r=>r.type==='cup'),e=x.finance.ledger.splice(i,1)[0];x.finance.balance-=e.amount;});corrupt(x=>x.career.minutes.g1--);
 const tied=s.cup.results.find(r=>r.penalties);assert.ok(tied);const index=s.cup.results.indexOf(tied);corrupt(x=>x.cup.results[index].penalties=[5,5]);corrupt(x=>x.cup.results[index].kicks[0].push(true));
 const partial=firstCup(549);F.begin(partial.match);F.tick(partial.match);const bad=copy(partial);bad.match.rng++;assert.throws(()=>S.restore(bad));assert.doesNotThrow(()=>S.restore(copy(partial)));
});

test('winning all three cup rounds pays every advance bracket once and records the club trophy',()=>{
 const s=complete(boosted(556));assert.equal(s.cup.champion,S.own);const rows=s.finance.ledger.filter(e=>e.type==='cup');assert.equal(rows.length,3);assert.deepEqual(rows.map(e=>e.stage),[0,1,2]);assert.deepEqual(rows.map(e=>e.advanceBonus),[12000,22000,50000]);assert.ok(rows.every(e=>e.winner===S.own));assert.equal(ownResults(s).length,3);assert.equal(s.finance.balance,s.finance.opening+s.finance.ledger.reduce((n,e)=>n+e.amount,0));for(const p of Object.values(s.squad))assert.equal(p[F.roleKey(p)],99);assert.equal(s.career.missions.growth,null);assert.doesNotThrow(()=>S.restore(copy(s)));const next=S.nextSeason(s);assert.equal(next.history[0].cupChampion,S.own);assert.equal(next.finance.balance,s.finance.balance);assert.equal(next.history.filter(h=>h.cupChampion===S.own).length,1);assert.equal(next.cup.champion,null);assert.doesNotThrow(()=>S.restore(copy(next)));
 const ghost=copy(next);ghost.history[0].cupChampion=S.clubs.find(c=>c.id!==S.own).id;assert.throws(()=>S.restore(ghost));
 const wrongPair=copy(next),past=wrongPair.finance.ledger.find(e=>e.type==='cup'),other=S.clubs.find(c=>c.id!==past.home&&c.id!==past.away).id;if(past.home===S.own)past.away=other;else past.home=other;assert.throws(()=>S.restore(wrongPair));
 const wrongWinner=copy(next),receipt=wrongWinner.finance.ledger.find(e=>e.type==='cup'),old=receipt.amount;receipt.winner=receipt.home===S.own?receipt.away:receipt.home;receipt.advanceBonus=0;receipt.income=receipt.gate;receipt.amount=receipt.income;wrongWinner.finance.balance+=receipt.amount-old;assert.throws(()=>S.restore(wrongWinner));
});

test('completed seasons record a single cup champion and carry cash and player development forward',()=>{
 const s=complete(S.create(552));assert.equal(s.round,14);assert.equal(s.match,null);assert.equal(s.cup.stage,3);const n=S.nextSeason(s);assert.equal(n.year,2);assert.equal(n.history[0].cupChampion,s.cup.champion);assert.equal(n.finance.balance,s.finance.balance);assert.equal(n.cup.stage,0);assert.equal(n.cup.originRound,0);assert.equal(n.cup.enabled,true);assert.equal(n.cup.champion,null);assert.equal(n.cup.results.length,0);assert.equal(n.history.length,1);for(const p of Object.values(n.squad)){assert.equal(p.xp,s.squad[p.id].xp);assert.equal(p[F.roleKey(p)],s.squad[p.id][F.roleKey(p)]);}assert.doesNotThrow(()=>S.restore(copy(n)));assert.throws(()=>S.nextSeason(n));
});

test('v4 academy careers at round 4 migrate every match phase without changing contracts, money or missions',()=>{
 const old=legacy();let original=old.S.scout(old.S.create(553),'FW');original=old.S.recruit(original,original.career.reports[0].candidates[0],'f1');for(let r=0;r<4;r++){old.S.train(original,'technique');finish(original.match,old.F);original=old.S.settle(original);}const saves=[copy(original)];old.F.begin(original.match);old.F.finishSegment(original.match);old.F.swap(original.match,'f2','f4');saves.push(copy(original));old.F.begin(original.match);old.F.finishSegment(original.match);saves.push(copy(original));old.F.begin(original.match);old.F.finishSegment(original.match);saves.push(copy(original));
 for(const raw of saves){const migrated=S.restore(copy(raw));assert.equal(migrated.version,8);assert.equal(migrated.competition,'league');assert.equal(migrated.cup.originRound,4);assert.equal(migrated.cup.enabled,true);assert.equal(migrated.cup.results.length,0);assertMatchPreserved(migrated.match,raw.match);assert.deepEqual(migrated.squad,legacySquad(raw.squad));assert.deepEqual(migrated.finance,raw.finance);for(const key of ['year','originRound','originLedger','reports','baselines','minutes','missions'])assert.deepEqual(migrated.career[key],raw.career[key]);assert.deepEqual(C.progress(migrated),copy(old.C.progress(raw)));assert.doesNotThrow(()=>S.restore(copy(migrated)));const next=settleMatch(migrated);assert.equal(next.round,5);assert.equal(next.competition,'cup');assert.equal(next.cup.stage,0);assert.doesNotThrow(()=>S.restore(copy(next)));}
});

test('v4 late-season saves defer all cup rounds until league completion and block a premature next season',()=>{
 const old=legacy();let original=old.S.create(554);for(let r=0;r<13;r++){finish(original.match,old.F);original=old.S.settle(original);}let s=S.restore(copy(original));assert.equal(s.round,13);assert.equal(s.competition,'league');assert.equal(s.cup.originRound,13);assert.equal(s.cup.results.length,0);assertMatchPreserved(s.match,copy(original.match));s=settleMatch(s);assert.equal(s.round,14);assert.equal(s.competition,'cup');rejectAtomic(s,x=>S.nextSeason(x));assert.doesNotThrow(()=>S.restore(copy(s)));while(s.competition==='cup'){const round=s.round;s=settleMatch(s);assert.equal(s.round,round);assert.doesNotThrow(()=>S.restore(copy(s)));}assert.equal(s.match,null);assert.equal(s.cup.stage,3);assert.equal(s.cup.results.length,7);assert.equal(s.finance.ledger.filter(e=>e.type==='goal').length,1);assert.equal(s.finance.ledger.filter(e=>e.type==='match').length,14);assert.equal(S.nextSeason(s).year,2);
});

test('v4 completed seasons get no retroactive cup or money and enable the cup in the following season',()=>{
 const old=legacy();let original=old.S.create(555);while(original.round<14){finish(original.match,old.F);original=old.S.settle(original);}const s=S.restore(copy(original));assert.equal(s.round,14);assert.equal(s.match,null);assert.equal(s.cup.enabled,false);assert.equal(s.cup.results.length,0);assert.deepEqual(s.finance,copy(original.finance));assert.equal(s.finance.ledger.filter(e=>e.type==='cup').length,0);assert.doesNotThrow(()=>S.restore(copy(s)));const n=S.nextSeason(s);assert.equal(n.cup.enabled,true);assert.equal(n.cup.originRound,0);assert.equal(n.history[0].cupChampion,null);assert.equal(n.finance.balance,s.finance.balance);assert.doesNotThrow(()=>S.restore(copy(n)));
});

test('promotion changes the cup field and historical champions replay in their original division',()=>{
 const lower=complete(boosted(121));assert.ok(S.standings(lower).find(c=>c.id===S.own).rank<=2);let upper=S.nextSeason(lower);assert.equal(upper.league.division,1);const members=S.leagueClubs(upper).map(c=>c.id);assert.deepEqual([...upper.cup.bracket].sort(),[...members].sort());assert.ok(upper.cup.bracket.filter(id=>id!==S.own).every(id=>!lower.cup.bracket.includes(id)));assert.equal(upper.history[0].cupChampion,lower.cup.champion);
 while(upper.competition!=='cup')upper=settleMatch(upper);assert.equal(upper.round,4);assert.ok(members.includes(S.opponentFor(upper).id));for(const stop of [0,45,65,90]){const original=copy(upper);while(original.match.minute<stop){if(!F.running(original.match))F.begin(original.match);F.finishSegment(original.match);}const restored=S.restore(copy(original));assertMatchPreserved(restored.match,original.match);finish(original.match);finish(restored.match);assert.deepEqual(S.settle(original),S.settle(restored));}
 const ended=complete(upper),next=S.nextSeason(ended);assert.equal(next.history[0].division,2);assert.equal(next.history[1].division,1);assert.equal(next.history[1].cupChampion,ended.cup.champion);assert.deepEqual(S.restore(copy(next)),next);const bad=copy(next);bad.history[1].cupChampion=S.clubs.find(c=>c.id!==S.own&&!members.includes(c.id)).id;assert.throws(()=>S.restore(bad));
});

console.log('Cup tests passed: '+checks+' groups.');
