const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),F=require('./dist/engine.js');
const clone=value=>JSON.parse(JSON.stringify(value));
function oldEngine(folder='legacy-v7'){const context=vm.createContext({});vm.runInContext(fs.readFileSync(path.join(__dirname,folder,'engine.js'),'utf8'),context);return context.Football;}
function coreLogs(logs){return clone(logs).map(event=>{for(const key of ['scorerId','scorerIdentity','assistId','assistIdentity'])delete event[key];return event;});}
function canonicalNames(value){const out=JSON.parse(JSON.stringify(value));const visit=o=>{if(!o||typeof o!=='object')return;if(typeof o.name==='string'){const p=F.identityProfile(o.identity||o.id);if(p)o.name=p.name;}for(const v of Object.values(o))visit(v);};visit(out);return out;}
function displayLogs(logs,players){return JSON.parse(JSON.stringify(logs)).map(e=>({...e,text:F.displayText(e.text,players)}));}
let checks=0;const test=(label,fn)=>{fn();checks++;console.log('PASS '+label);};
const complete=s=>{while(s.phase!=='full'){if(!F.running(s))F.begin(s);F.finishSegment(s);}return s;};
test('formations preserve 11 unique players and one goalkeeper',()=>{for(const key of ['442','433','352','442']){const s=F.create();F.setFormation(s,key);assert.equal(s.lineup.length,11);assert.equal(new Set(s.lineup).size,11);assert.equal(s.lineup.filter(id=>s.players[id].pos==='GK').length,1);assert.equal(Object.keys(s.players).length-s.lineup.length,7);for(const [pos,count] of Object.entries(F.formations[key]))assert.equal(s.lineup.filter(id=>s.players[id].pos===pos).length,count);}});
test('illegal changes fail without changing the match',()=>{const s=F.create();let before=JSON.stringify(s);assert.throws(()=>F.swap(s,'f1','m5'));assert.equal(JSON.stringify(s),before);assert.throws(()=>F.setFormation(s,'555'));assert.equal(JSON.stringify(s),before);F.begin(s);before=JSON.stringify(s);assert.throws(()=>F.swap(s,'f1','m5'));assert.throws(()=>F.setTactic(s,'unknown'));assert.throws(()=>F.setFormation(s,'433'));assert.equal(JSON.stringify(s),before);complete(s);before=JSON.stringify(s);assert.throws(()=>F.swap(s,'f1','f3'));assert.throws(()=>F.setTactic(s,'press'));assert.equal(JSON.stringify(s),before);});
test('three substitutions maximum, no re-entry and same-position only',()=>{const s=F.create();F.begin(s);F.finishSegment(s);F.swap(s,'f1','f3');F.swap(s,'d1','d5');F.swap(s,'m1','m5');assert.equal(s.subs,3);assert.throws(()=>F.swap(s,'f3','f1'));assert.throws(()=>F.swap(s,'g1','g2'));assert.equal(s.subs,3);assert.equal(new Set(s.lineup).size,11);});
test('version 10 uses five substitutions in three windows while halftime stays free',()=>{const s=F.create(20261010,{version:10});assert.deepEqual(F.substitutionRules(s),{limit:5,windowLimit:3,windows:0});F.begin(s);F.tick(s);F.swap(s,'f1','f3');assert.equal(s.subWindows,1);F.swap(s,'d1','d5');assert.equal(s.subWindows,1);while(s.minute<20)F.tick(s);F.swap(s,'m1','m5');assert.equal(s.subWindows,2);F.finishSegment(s);F.swap(s,'f2','f4');assert.equal(s.subWindows,2);F.begin(s);while(s.minute<65)F.tick(s);F.swap(s,'d2','d6');assert.equal(s.subs,5);assert.equal(s.subWindows,3);assert.throws(()=>F.swap(s,'m2','m6'),/교체 가능 인원|교체 기회/);assert.doesNotThrow(()=>F.restore(clone(s)));});
test('halftime changes preserve the complete first half',()=>{const s=F.create();F.begin(s);F.finishSegment(s);const prefix=JSON.stringify(s.logs),score=[...s.score],first=JSON.stringify(s.segments[0]);F.swap(s,'f1','f3');F.setTactic(s,'counter');assert.deepEqual(s.score,score);assert.equal(JSON.stringify(s.segments[0]),first);assert.equal(JSON.stringify(s.logs.slice(0,JSON.parse(prefix).length)),prefix);});
test('all players total 990 minutes; substitutes and bench use correct energy',()=>{const s=F.create();F.begin(s);F.finishSegment(s);let outgoing=s.players.f1.energy;F.swap(s,'f1','f3');complete(s);assert.equal(Object.values(s.players).reduce((n,p)=>n+p.minutes,0),990);assert.equal(s.players.f1.minutes,45);assert.equal(s.players.f3.minutes,45);assert.equal(s.players.f1.energy,outgoing);assert.equal(s.players.g2.minutes,0);assert.equal(s.players.g2.energy,100);assert.ok(Math.abs(s.players.f3.energy-(100-35*(1+(50-77)/250)*.5))<1e-8);});
test('save-resume is deterministic during play and at both decision points',()=>{for(const stop of [17,45,56,65,78]){const a=F.create(20260930);while(a.minute<stop){if(!F.running(a))F.begin(a);F.tick(a);}const b=F.restore(JSON.parse(JSON.stringify(a)));b.paused=false;complete(a);complete(b);assert.deepEqual(a.score,b.score);assert.deepEqual(a.logs,b.logs);assert.equal(a.rng,b.rng);assert.deepEqual(a.players,b.players);}});
test('press increases opportunities, risk and energy; fast forward preserves results',()=>{const a=F.create(),b=F.create();F.setTactic(b,'press');assert.ok(F.ratings(b).ourRate>F.ratings(a).ourRate);assert.ok(F.ratings(b).oppRate>F.ratings(a).oppRate);complete(a);complete(b);assert.ok(b.players.f1.energy<a.players.f1.energy);const c=F.create();while(c.phase!=='full'){if(!F.running(c))F.begin(c);F.tick(c);}assert.deepEqual(a.score,c.score);assert.deepEqual(a.logs,c.logs);});
test('matches continue if every starting forward is sent off',()=>{let witnessedChance=false;for(let seed=1;seed<=24;seed++){const s=F.create(seed);F.begin(s);const forwards=s.lineup.filter(id=>s.players[id].pos==='FW');assert.ok(forwards.length);s.discipline={version:1,events:forwards.map((id,index)=>({minute:index+1,team:0,id,card:'red',reason:'direct-red'}))};while(s.phase!=='full'){if(!F.running(s))F.begin(s);F.tick(s);}witnessedChance ||= s.chances[1]>0;}assert.ok(witnessedChance,'at least one deterministic test match reached an opponent chance without any active forwards');});
test('fast forward gains counter pace quality but trades away finishing',()=>{const s=F.create();F.setTactic(s,'counter');const before=F.ratings(s);F.swap(s,'f1','f3');const after=F.ratings(s);assert.ok(after.paceBonus>before.paceBonus);assert.ok(after.pace>before.pace);assert.ok(s.players.f3.attack<s.players.f1.attack);assert.equal(s.subs,0);});
test('all formations/tactics finish with bounded energy and coherent stats',()=>{for(const formation of ['442','433','352'])for(const tactic of ['press','balanced','counter'])for(let seed=1;seed<=80;seed++){const s=F.create(seed);F.setFormation(s,formation);F.setTactic(s,tactic);complete(s);assert.equal(s.minute,90);assert.equal(s.segments.length,3);assert.equal(Object.values(s.players).reduce((n,p)=>n+p.minutes,0),990);for(const p of Object.values(s.players))assert.ok(p.energy>=0&&p.energy<=100);for(let t=0;t<2;t++){assert.ok(s.score[t]<=s.shots[t]&&s.shots[t]<=s.chances[t]);assert.equal(s.logs.filter(l=>l.type==='goal'&&l.team===t).length,s.score[t]);assert.equal(s.segments.reduce((n,g)=>n+g.goals[t],0),s.score[t]);assert.ok(Math.abs(s.segments.reduce((n,g)=>n+g.xg[t],0)-s.xg[t])<1e-8);}}});
test('malformed phase, missing segment and broken stats are rejected',()=>{let bad=F.create();bad.phase='first';assert.throws(()=>F.restore(bad));const s=F.create();F.begin(s);F.tick(s);for(const mutate of [x=>x.minute=90,x=>x.segments=[],x=>x.shots[0]=99,x=>x.players.f1.minutes=0]){let altered=JSON.parse(JSON.stringify(s));mutate(altered);assert.throws(()=>F.restore(altered));}assert.equal(F.restore(F.create()).phase,'prep');});
test('goal attribution keeps all eight RNG draws and legacy match outcomes unchanged',()=>{
 const old=oldEngine();for(const seed of [1,37,121,20260930]){const a=old.create(seed),b=F.create(seed);let expectedRng=seed>>>0;old.setTactic(a,'counter');F.setTactic(b,'counter');while(a.phase!=='full'){if(!old.running(a)){old.begin(a);F.begin(b);}old.tick(a);F.tick(b);for(let draw=0;draw<8;draw++)expectedRng=(Math.imul(expectedRng,1664525)+1013904223)>>>0;assert.equal(a.rng,expectedRng);assert.equal(b.rng,expectedRng);for(const key of ['score','shots','chances','xg'])assert.deepEqual(b[key],clone(a[key]));if(a.minute===45){old.swap(a,'f1','f3');F.swap(b,'f1','f3');old.setTactic(a,'press');F.setTactic(b,'press');}if(a.minute===65){old.swap(a,'m1','m5');F.swap(b,'m1','m5');old.setTactic(a,'balanced');F.setTactic(b,'balanced');}}
 assert.deepEqual(displayLogs(coreLogs(b.logs),b.players),displayLogs(a.logs,a.players));assert.deepEqual(b.segments,clone(a.segments));assert.deepEqual(b.players,canonicalNames(a.players));assert.equal(b.statisticsOriginMinute,0);assert.equal(F.goalAttributions(b).length,b.score[0]);assert.doesNotThrow(()=>F.restore(clone(b)));}
});
test('version 6 gives each minute one coherent attack and saves named cross and cutback actions',()=>{
 const actions=new Set();for(let seed=1;seed<=16;seed++){const a=F.create(seed,{version:6}),b=F.create(seed,{version:6});F.setFormation(a,'433');F.setFormation(b,'433');F.begin(a);F.begin(b);while(a.minute<37){F.tick(a);F.tick(b);}const resumed=F.restore(clone(a));resumed.paused=false;while(a.phase!=='full'){if(!F.running(a))F.begin(a);if(!F.running(resumed))F.begin(resumed);F.tick(a);F.tick(resumed);}assert.deepEqual(resumed.logs,a.logs);assert.deepEqual(resumed.score,a.score);const events=a.logs.filter(event=>['goal','shot','chance'].includes(event.type));for(const event of events){actions.add(event.action);assert.ok(['cross','cutback','through_ball','dribble','combination'].includes(event.action));assert.ok(['left','right'].includes(event.side));if(event.team===0){assert.ok(a.lineup.includes(event.actorId)||a.segments.some(segment=>segment.lineup.includes(event.actorId)));assert.ok(event.sourceId);if(event.type==='goal')assert.equal(event.actorId,event.scorerId);}}assert.equal(new Set(events.map(event=>event.minute)).size,events.length,'only one side can attack in a minute');assert.equal(events.length,a.chances[0]+a.chances[1]);assert.doesNotThrow(()=>F.restore(clone(a)));}
 assert.deepEqual(actions,new Set(['cross','cutback','through_ball','dribble','combination']));const match=complete(F.create(6,{version:6})),event=match.logs.find(row=>row.action);assert.ok(event);for(const mutate of [x=>x.logs.find(row=>row.action).action='teleport',x=>x.logs.find(row=>row.action).side='centre',x=>x.logs.find(row=>row.action).actorId='g1']){const bad=clone(match);mutate(bad);assert.throws(()=>F.restore(bad));}
});
test('v1 through v4 migration preserves old goals and attributes only goals after the saved minute',()=>{
 const old=oldEngine();for(const version of [1,2,3,4])for(const stop of [0,17,45,65,90]){const original=old.create(20260930);while(original.minute<stop){if(!old.running(original))old.begin(original);old.tick(original);}const raw=clone(original);raw.version=version;const migrated=F.restore(raw);assert.equal(migrated.version,5);assert.equal(migrated.statisticsOriginMinute,stop);assert.deepEqual(migrated.logs,clone(original.logs));assert.equal(F.goalAttributions(migrated).length,0);assert.equal(migrated.rng,original.rng);while(original.phase!=='full'){if(!old.running(original))old.begin(original);old.finishSegment(original);}complete(migrated);for(const key of ['score','shots','chances','xg','rng'])assert.deepEqual(migrated[key],clone(original[key]));assert.deepEqual(displayLogs(coreLogs(migrated.logs),migrated.players),displayLogs(original.logs,original.players));assert.equal(F.goalAttributions(migrated).length,migrated.logs.filter(event=>event.type==='goal'&&event.team===0&&event.minute>stop).length);assert.ok(migrated.logs.filter(event=>event.type==='goal'&&event.team===0&&event.minute<=stop).every(event=>!Object.hasOwn(event,'scorerId')));assert.deepEqual(F.restore(clone(migrated)),migrated);}
});
test('scorers and assists use canonical contracts and only the players on the field at the goal',()=>{
 const players=Object.fromEntries(F.roster.map(p=>[p.id,{...p,energy:100,injury:p.id==='f2'?{remaining:1}:null}]));players.f1={...F.profileForSlot('f1','t_f1'),injury:null};const match=F.create(20260930,{players});if(match.lineup.includes('f4'))F.swap(match,'f4','f3');F.begin(match);F.finishSegment(match);F.swap(match,'f1','f4');complete(match);const goals=F.goalAttributions(match);assert.ok(goals.some(goal=>goal.scorerIdentity==='t_f1'));for(const goal of goals){const segment=match.segments.find(segment=>goal.minute>segment.start&&goal.minute<=segment.end),scorer=match.players[goal.scorerId];assert.ok(segment.lineup.includes(goal.scorerId));assert.equal(scorer.pos,'FW');assert.equal(goal.scorerIdentity,scorer.identity);assert.notEqual(goal.scorerId,'f2');if(goal.minute>45)assert.notEqual(goal.scorerId,'f1');if(goal.assistId!==null){const assist=match.players[goal.assistId];assert.ok(segment.lineup.includes(assist.id));assert.notEqual(assist.pos,'GK');assert.notEqual(assist.id,scorer.id);assert.equal(goal.assistIdentity,assist.identity);assert.notEqual(assist.id,'f2');if(goal.minute>45)assert.notEqual(assist.id,'f1');}else assert.equal(goal.assistIdentity,null);}assert.doesNotThrow(()=>F.restore(clone(match)));const solo=complete(F.create(3));assert.ok(F.goalAttributions(solo).some(goal=>goal.assistId===null&&goal.assistIdentity===null));assert.doesNotThrow(()=>F.restore(clone(solo)));
});
test('malformed attribution, unavailable players, changed origin and extra goal logs are rejected',()=>{
 const match=complete(F.create(20260930)),index=match.logs.findIndex(event=>event.type==='goal'&&event.team===0);assert.ok(index>=0);for(const mutate of [x=>x.statisticsOriginMinute=-1,x=>x.statisticsOriginMinute=.5,x=>x.statisticsOriginMinute=91,x=>x.statisticsOriginMinute=45,x=>delete x.statisticsOriginMinute,x=>delete x.logs[index].scorerId,x=>x.logs[index].scorerIdentity='t_f1',x=>{x.logs[index].scorerId='f3';x.logs[index].scorerIdentity='f3';},x=>{x.logs[index].scorerId='f2';x.logs[index].scorerIdentity='f2';},x=>{x.logs[index].assistId='g1';x.logs[index].assistIdentity='g1';},x=>{x.logs[index].assistId='m5';x.logs[index].assistIdentity='m5';},x=>{x.logs[index].assistId=x.logs[index].scorerId;x.logs[index].assistIdentity=x.logs[index].scorerIdentity;},x=>x.logs[index].assistIdentity='unknown',x=>x.logs[index].assistId=null,x=>x.logs.push(clone(x.logs[index])),x=>x.logs[index].type='shot',x=>{x.logs[index].minute=0;},x=>{const log=x.logs.find(event=>event.type!=='goal');log.scorerId='f1';}]){const bad=clone(match);mutate(bad);assert.throws(()=>F.restore(bad));}assert.deepEqual(F.restore(clone(match)),match);
});
console.log('Validated '+checks+' groups across 720 complete simulated matches.');
for(const tactic of ['balanced','press','counter']){const s=F.create();F.begin(s);F.finishSegment(s);const half=[...s.score];F.setTactic(s,tactic);if(tactic==='counter')F.swap(s,'f1','f3');complete(s);console.log(JSON.stringify({tactic,half,full:s.score,xg:s.xg,shots:s.shots}));}
